version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: payflow-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: payflow-redis
    ports:
      - "6379:6379"

  nats:
    image: nats:latest
    container_name: payflow-nats
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  postgres_data:
