[package]
name = "shared-messaging"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
